name: NGM Indexer

on:
  schedule:
    - cron: '0 2 * * *' # Run daily at 2:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  build_index:
    runs-on: ubuntu-latest
    environment: "NGM Scrape"

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Start Cloud SQL Proxy
        uses: Jawafdehi/gce-cloudsql-proxy-action@master
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: ${{ secrets.CLOUD_SQL_INSTANCE }}
          port: 5432

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run index builder
        env:
          FILES_STORE: 's3://ngm'
          AWS_ENDPOINT_URL: 'https://4c96557d73194d4f245ba23bd6063ad5.r2.cloudflarestorage.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'auto'
          NGM_STORE_BASE_URL: https://ngm-store.jawafdehi.org
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROXY }}
        run: poetry run python -m ngm.index.build_index
