name: CI

on:
  push:
    branches: [ 'main*', 'develop*' ]
  pull_request:
    branches: [ 'main*', 'develop*' ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python + Poetry
        id: setup
        uses: ./.github/actions/setup-poetry-python

      - name: Check formatting
        run: ./scripts/format.sh --check

      - name: Run tests
        run: poetry run pytest --tb=short -q
